### ISSUE TITLE
[firefox] input框内输入下划线不显示

### ISSUE THREAD

**Issue by eightJie** [eightJie/css-debugger#1]
``` html
<input type="text" />
```

``` css
input{
 padding: 5px 10px;
 font-size: 12px;
 line-height: 12px;
}
```

如上代码，在firefox浏览器中，在输入框中输入下划线，下划线显示不出来，不知道是什么原因导致的，有什么好的修复方法么？
